name: hello-world
on: 
  push:
    branches:
      ACTION-001
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out repository-code
        uses: actions/checkout@v3
      - run: echo "Hello World"
      - run: echo "$(cat hello-world.txt)"
      - run: echo "$(host_ip=$(ping -c 1 host.docker.internal | grep 'PING' | awk -F '[()]' '{print $2}'))"
      - run: echo "Done!!!"
